# '''
# description:
#   - all keys which are in <> are optional - if they are not in dict(data) then they are ignored
#   - all capital keys {ENV_VAR} are computed first and eather coming from outside or inside
#
#   {project[name]}: str, full name of the project
#             example: C001_cool_commercial, D001_projectx
#
#   {project[code]}: str, shorter version of project name 2-4 letters usually
#             example: ccm, prj, dogz
#
#   {AVALON_SILO}: str, the highest folder in the hierarchy of the asset, legacy
#
#   {asset}: str, name of the entity, e.g. sh010, bob, 101sh020
#             example: sh010, bob, car-big, 101sh050, sq02
#
#   {asset.type}: str, type of the entity,
#             example: shot, asset, sequence, folder
#
#   {family}: str, general type of the published file
#             example: model, cache, render, look, rig
#
#   {subset}: str, a published part of an asset. Always contains family string too
#             example: modelMain, modelDamaged, renderMain, lookMain
#
#   {version}: int, example: 14
#
#   {frame}: int, a frame number in image sequences, example: 0001, 989, 49593
#
#   {representation}: str, example: abc, ma, nk, exr, png, curves, history, metadata
# '''

version_padding: 3
version: "v{version:0>{@version_padding}}"
frame_padding: 4
frame: "{frame:0>{@frame_padding}}"

resources:
  footage: "{root}/{project[name]}/resources/footage"
  reference: "{root}/{project[name]}/resources/reference"

work:
  folder: "{root}/{project[name]}/{hierarchy}/{asset}/work/{task}"
  file: "{project[code]}_{asset}_{task}_{@version}<_{comment}>.{ext}"
  path: "{root}/{project[name]}/{hierarchy}/{asset}/work/{task}/{project[code]}_{asset}_{task}_{@version}<_{comment}>.{ext}"

render:
  padding: "4"
  path: "{root}/{project[name]}/{hierarchy}/{asset}/publish/render/{subset}/v{version:0>3}/{project[code]}_{asset}_{task}_v{version:0>3}_{subset}<_{output}><.{frame}>.{representation}"

texture:
  path: "{root}/{project[name]}/{hierarchy}/{asset}/publish/{family}/{subset}"

publish:
  burninVersion: "{@version}"
  file: "{project[code]}_{asset}_{subset}_{@version}<_{output}><.{@frame}>.{representation}"
  folder: "{root}/{project[name]}/{hierarchy}/{asset}/publish/{family}/{subset}/{@version}"
  path: "{@folder}/{@file}"
  thumbnail: "{thumbnail_root}/{project[name]}/{_id}_{thumbnail_type}{ext}"

master:
  path: "{root}/{project[name]}/{hierarchy}/{asset}/publish/{family}/{subset}/master/{project[code]}_{asset}_{subset}_master<_{output}><.{frame}>.{representation}"
  folder: "{root}/{project[name]}/{hierarchy}/{asset}/publish/{family}/{subset}/master"

avalon:
  workfile: "{project[code]}_{asset}_{task}_{@version}<_{comment}>"
  work: "{root}/{project[name]}/{hierarchy}/{asset}/work/{task}"
  publish: "{root}/{project[name]}/{hierarchy}/{asset}/publish/{family}/{subset}/{@version}/{project[code]}_{asset}_{subset}_{@version}<_{output}><.{@frame}>.{representation}"
